name:                speed-comparison
version:             0.1.0.0
github:              "yutotakano/speed-comparison"
license:             BSD3
author:              "Yuto Takano"
maintainer:          "moa17stock@gmail.com"
copyright:           "2021 Yuto Takano"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/yutotakano/speed-comparison#readme>

dependencies:
- attoparsec
- megaparsec
- base >= 4.7 && < 5
- criterion
- regex-tdfa
- parsec
- text
- random

library:
  source-dirs: src

executables:
  run-comparison:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - speed-comparison

